services:
  besu:
    image: hyperledger/besu:25.2.2
    restart: unless-stopped
    network_mode: host
    volumes:
      - besudata:/var/lib/besu
    command: >
      --network=dev
      --rpc-http-cors-origins="all"
      --rpc-http-enabled
      --metrics-enabled
      --metrics-host=0.0.0.0
      --host-allowlist="*"
      --rpc-http-api=ETH,NET,WEB3,DEBUG,TXPOOL
      --rpc-ws-enabled
      --data-path=/var/lib/besu
      --rpc-ws-api=ETH,NET,WEB3
      --miner-enabled
      --miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
      --logging=INFO
      --rpc-http-max-active-connections=100000
      --min-gas-price=0
      --tx-pool-max-future-by-sender=1024

volumes:
  besudata: